# Generated by Django 6.0.3 on 2026-03-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_currentfocus_dailygoal_timeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeblock',
            name='user',
        ),
        migrations.DeleteModel(
            name='CurrentFocus',
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='TimeBlock',
        ),
    ]
